(require 'buff-menu+)
(require 'fix-buffers-list)
(require 'repository-root)
(live-load-config-file "web-mode-config.el")
(live-load-config-file "evil-config.el")
(live-load-config-file "psvn-config.el")
(live-load-config-file "grin-config.el")
(live-load-config-file "ack-and-half-config.el")
(live-load-config-file "javascript-config.el")
(live-load-config-file "minibuffer-config.el")
(live-load-config-file "python-config.el")
;;(live-load-config-file "recent-files-config.el")
(live-load-config-file "ediff-config.el")
(live-load-config-file "xplan-config.el")
(live-load-config-file "cscope-config.el")
(live-load-config-file "flycheck-config.el")
;;(live-load-config-file "ibuffer-config.el")
(live-load-config-file "notmuch-config.el")
(live-load-config-file "erlang-config.el")
(live-load-config-file "taskjuggler-config.el")
(live-load-config-file "twittering-config.el")
(live-load-config-file "jabber-config.el")
(live-load-config-file "orgmode-config.el")
(live-load-config-file "calfw-config.el")
(live-load-config-file "tail-config.el")
(live-load-config-file "server-config.el")
(live-load-config-file "tmux-config.el")
(live-load-config-file "elisp-config.el")
(live-load-config-file "eproject-config.el")
(live-load-config-file "modeline-config.el")
(live-load-config-file "idutils-config.el")
;;(live-load-config-file "jedi-config.el")
;;(live-load-config-file "ecb-config.el")
(live-load-config-file "helm-config.el")
(live-load-config-file "icicles-config.el")
(live-add-pack-lib "/usr/local/share/emacs/site-lisp/")
(live-load-config-file "dired-config.el")
(live-load-config-file "dired+-config.el")

(defun guess-where-keybinding-is-defined (key)
  "try to guess where a key binding might be defined"
  (interactive (list (read-key-sequence "Describe key: ")))
  (let ((bindings (minor-mode-key-binding key))
        found)
    (while (and bindings (not found))
      (if (setq found (caar bindings))
          (find-function (cdar bindings)))
      (setq bindings (cdr bindings)))))
